name: Release
description: Create a GitHub Release and Publish to pub.dev

inputs:
  github_token:
    description: "GitHub token to request GitHub API"
    required: true
  tag:
    description: "The tag name of the release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: dart-lang/setup-dart@e630b99d28a3b71860378cafdc2a067c71107f94 # v1.7.0
      with:
        sdk: '3.6'

    - name: Install dependencies
      run: dart pub get

    - name: Analyze project source (ignore example)
      run: dart analyze lib

    - name: Run tests
      run: dart test

    - name: Publish to pub.dev
      uses: dart-lang/setup-dart/.github/workflows/publish.yml@e630b99d28a3b71860378cafdc2a067c71107f94 # v1.7.0
      with:
        environment: pub.dev
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048 # v2.2.0
      with:
        body_path: CHANGELOG.md
        tag_name: ${{ inputs.tag }}
        token: ${{ inputs.github_token }}
