name: Dart CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d # v1.8.1
        with:
          sdk: '3.8'

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source (ignore example)
        run: dart analyze lib

      - name: Run tests
        run: dart test
